title: Blogs
description: My personal stuff
author: Arham Jain
github: https://github.com/arham-jain
about: A developer trying to build and learn stuff!
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/arhamajain"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/arham-jain/"
    - icon: fa-stack-overflow
      link: "https://stackoverflow.com/users/8727628/abaa"
    - icon: fa-github
      link: "https://github.com/arham-jain"

share:
  twitter_username: github.io

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://arham-jain.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
